### PR TITLE
major ground breaking improvement

### PR DESCRIPTION
**Pull request by raizam**

### CODE REVIEW

**Comment by nem0** [comment]
fuck that contribution

**Comment by nem0** [comment]
I'm reconsidering - reopen

**Comment by raizam** [comment]
thank you for reconsidering lot of work here

**Comment by nem0** [comment]
:D :D the first one was wrong :D

**Comment by nem0** [comment]
I reconsidered - fuck that contribution

**Comment by raizam** [comment]
you ruined all my work
fuck you @nem0 
yeah fuck you!

**Comment by raizam** [comment]
:trollface:

**Comment by dimapolkjui** [comment]
Merry christmas everyone!

**Comment by nem0** [comment]
@dimapolkjui we are all going to die here

**Pull request closed without merging**
